### PR TITLE
WIP: Add italian localization

### PR DESCRIPTION
**Pull request by zanhk**
@kyoshino I will work on this tomorrow, if in the future you need to add more localization keys just put the english one and ping me.

### CODE REVIEW

**Comment by zanhk** [comment]
@kyoshino Can you connect the issue https://github.com/sveltia/sveltia-cms/issues/70? thanks

**Comment by kyoshino** [comment]
I really appreciate this, but it’s too early to start l10n. (The Japanese l10n exists because I’ve developed this CMS for my clients, who are mostly in Japan.)

Since many features are [still missing](https://github.com/sveltia/sveltia-cms#compatibility), many strings will be added before 1.0, including many invisible labels for accessibility. I’ll keep #70 open and ping you early next year when the strings are better organized and more stable.

Actually, the string format may also change. The current library is [svelte-i18n](https://github.com/kaisermann/svelte-i18n), but I’ll evaluate [other options](https://github.com/sveltejs/kit/issues/553) since it doesn’t even support singular/plural switches. Some locales are complicated — [Fluent](https://projectfluent.org/) (created for Mozilla Firefox, [svelte-fluent](https://github.com/nubolab-ffwd/svelte-fluent)) might be a better choice.

Let me know if you have an opinion for Italian 🙂 (Japanese is too simple, there is no plural form, gender or whatever)

**Comment by kyoshino** [comment]
_Tip_: When you write “Fix #70”, “Close #70”, etc. in the pull request description, the PR and issue will be automatically linked, and the issue will be automatically closed when the PR is merged. 😺 See:

- https://github.blog/2013-05-14-closing-issues-via-pull-requests/
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by zanhk** [comment]
> I really appreciate this, but it’s too early to start l10n. (The Japanese l10n exists because I’ve developed this CMS for my clients, who are mostly in Japan.)
> 
> Since many features are [still missing](https://github.com/sveltia/sveltia-cms#compatibility), many strings will be added before 1.0, including many invisible labels for accessibility. I’ll keep #70 open and ping you early next year when the strings are better organized, polished, and more stable.
> 
> Actually, the string format may also change. The current library is [svelte-i18n](https://github.com/kaisermann/svelte-i18n), but I’ll evaluate [other options](https://github.com/sveltejs/kit/issues/553) since it doesn’t even support singular/plural switches. Some locales are complicated — [Fluent](https://projectfluent.org/) (created for Mozilla Firefox, [svelte-fluent](https://github.com/nubolab-ffwd/svelte-fluent)) might be a better choice.
> 
> Let me know if you have an opinion on Italian 🙂 (Japanese is too simple, there is mostly no plural form, gender, or whatever)
> 
> _Edit_: I’ve realized that the Fluent homepage has an Italian example, which shows a lowercase variant.
> 
> _Edit_: I think I’ll create my own Svelte wrapper for Fluent.js.

Ok

**Comment by kyoshino** [comment]
I’ve added [README for localizers](https://github.com/sveltia/sveltia-cms/blob/main/src/lib/locales/README.md) 😅 You’re good as you’ve filed an issue!

**Pull request closed without merging**
