### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by RDjarbeng**
Added table of contents for the current readme so visitors can skip to the section they are interested in directly.

### CODE REVIEW

**Comment by RDjarbeng** [comment]
I've seen the comment in the contributing.md that pull requests may not be accepted unless for small file changes, hope this counts as a small change

**Comment by kyoshino** [comment]
Does it actually add TOC to Markdown? I don’t see anything in the [preview](https://github.com/sveltia/sveltia-cms/blob/b175d6bc7ad2a7d245d2d5eb17705bf3deffb025/README.md) other than the plain “Table of contents” text.

GitHub actually shows [TOC on README](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/) but I know it’s not intuitive, so I agree to add TOC to the Markdown body.

**Comment by RDjarbeng** [comment]
Yes the default TOC it's not very intuitive. I had to scroll all the way the first time I visited the repo. I actually found out about the GitHub TOC when creating this PR.

Sorry it seems the full table of contents was not shown initially. I've corrected it, now it shows in the [preview](https://github.com/RDjarbeng/sveltia-cms/blob/patch-1/README.md)

**Comment by RDjarbeng** [comment]
Oh I just corrected the issues raised, and the Pull request got closed?

**Comment by RDjarbeng** [comment]
@kyoshino

**Comment by kyoshino** [comment]
Ah sorry, I’ve added a TOC myself before seeing your latest comment. I don’t think we need a full TOC anyway.

**Review by kyoshino — CHANGES_REQUESTED** [review]
Well, it’s better to show more headings as suggested. But can you please 

- Remove h1 (Sveltia CMS) to start with h2
- Move the TOC after the first paragraph (“Sveltia CMS is a Git-based lightweight headless CMS...”) for SEO

**Comment by RDjarbeng** [comment]
Made the requested changes

**Comment by RDjarbeng** [comment]
Also can I suggest that you move the Getting started section a bit closer to the top? Or maybe that should be a different PR

**Review by kyoshino — CHANGES_REQUESTED** [review]
The content order is fine, but nitpicks:

- De-indent the entire TOC (no 2 leading spaces)
- Remove an extra blank line after Disclaimer (1 line is fine)

Actually, you can automatically format the file by simply saving it (Ctrl/Cmd+S) in VS Code if the Prettier extension is installed 😄

**Comment by RDjarbeng** [comment]
I have made the changes

**Comment by RDjarbeng** [comment]
About prettier, I keep getting this error about failing to resolve the parser. I haven't been able to resolve that but since it's another issue on it's own I have chosen to ignore it.

' Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser....'

image

**Review by kyoshino — APPROVED** [review]
Not sure about the Prettier error, but the change now LGTM. Thanks! 💯

**Pull request merged**
